### ISSUE TITLE
I suggest using dictionaries for pickling (otherwise you might forget in what order to set the list elements and not be able to extract the information meaningfully anymore over time))

### ISSUE THREAD

**Issue by fraboeni** [InaFen/DkNN#1]
https://github.com/InaFen/DkNN/blob/555a9e31b98d6c05653c0ac2c79b4218430a65ef/dknn_analysis_neighbors.py#L333

**Comment by InaFen** [comment]
I changed the code accordingly, so now dictionaries are used for pickling (c4f6b856c33c12b2ab95a24cb8b3f28e30692794).
