### ISSUE TITLE
it would be great to document all the functions in this file better. 

### ISSUE THREAD

**Issue by fraboeni** [InaFen/DkNN#3]
https://github.com/InaFen/DkNN/blob/c4f6b856c33c12b2ab95a24cb8b3f28e30692794/utils/utils.py#L9

Some functions use parameters that are not documented, and it would be super helpful to add the type of data that is expected for each argument (list, dict, numpy array of shape with elements of types, etc.)

**Comment by InaFen** [comment]
Thank you, I adapted the functions accordingly (96c76fc3eac3d3648910b50cbe0f13fc2180df32).
